# DataFetcher 클래스 테스트

이 노트북은 `DataFetcher` 클래스의 모든 메서드가 정상적으로 동작하는지 확인하기 위한 테스트 코드를 포함합니다.
각 섹션은 특정 메서드에 대한 테스트를 수행합니다.

## 1. 환경 설정 및 초기화
`DataFetcher` 인스턴스를 생성합니다.

In [1]:
import lawdigest_data_pipeline as data_pipeline
import pandas as pd
from datetime import datetime, timedelta

# Fetcher 인스턴스 생성 
fetcher = data_pipeline.DataFetcher()
print("DataFetcher initialized.")

/home/ubuntu/project/lawdigest/lawdigestenv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

DataFetcher initialized.

## 2. 국회의원 데이터 수집 (`fetch_lawmakers_data`)
현직 국회의원 명단과 정보를 수집합니다.

In [2]:
lawmakers_df = fetcher.fetch_lawmakers_data()

if lawmakers_df is not None and not lawmakers_df.empty:
    print(f"Successfully fetched {len(lawmakers_df)} lawmakers.")
    display(lawmakers_df.head(3))
else:
    print("Failed to fetch lawmakers data.")

📌 [국회의원 데이터 수집 시작]
➡️  첫 페이지 요청하여 전체 데이터 개수 확인 중...

📥 데이터 수집 중: 100%|██████████| 298/298 [00:00<00:00, 311.21개/s]

🎉 다운로드 완료! 총 298개의 데이터를 수집했습니다. 📊
✅ [INFO] 다운로드 완료! 총 소요 시간: 0.94초
✅ [INFO] 총 298 개의 의원 데이터 수집됨
Successfully fetched 298 lawmakers.

,HG_NM,HJ_NM,ENG_NM,BTH_GBN_NM,BTH_DATE,JOB_RES_NM,POLY_NM,ORIG_NM,ELECT_GBN_NM,CMIT_NM,...,SEX_GBN_NM,TEL_NO,E_MAIL,HOMEPAGE,STAFF,SECRETARY,SECRETARY2,MONA_CD,MEM_TITLE,ASSEM_ADDR
0,강경숙,姜景淑,KANG KYUNGSOOK,음,1967-05-02,위원,조국혁신당,비례대표,비례대표,교육위원회,...,여,02-784-5601,gracesook52@rebuildingk.kr,https://blog.naver.com/grace6752,"김재삼, 서용선","김홍, 오세령","박문혁, 김예닮, 이경열, 김희경, 공병준",T2T8225E,2024.5~ 제22대 국회의원 (비례대표/조국혁신당)\n2021.2~2023.2 ...,의원회관 515호
1,강대식,姜大植,KANG DAESIK,음,1959-11-02,간사,국민의힘,대구 동구군위군을,지역구,국방위원회,...,남,02-784-5275,kds21341@naver.com,None,"박홍규, 유진영","김기일, 이기백","박순권, 김현정, 박동혁, 이정은",L2I9861C,[학력]\n송정초등학교\n안심중학교\n경북대학교 사범대학 부속고등학교\n영남대학교 ...,의원회관 341호
2,강득구,姜得求,KANG DEUKGU,양,1963-05-27,위원,더불어민주당,경기 안양시만안구,지역구,"기후위기 특별위원회, 기후에너지환경노동위원회",...,남,02-784-2747~9,mainsail440@daum.net,http://blog.naver.com/dulipapa,"정진태, 최경순","김창용, 홍미하","윤경민, 김재기, 김유나, 박시연",8P37634C,2024. 5. ~ 현재 국회 환경노동위원회 위원 \n2024. 2. ...,의원회관 814호

## 3. 법안 데이터 수집 (`fetch_bills_data`)
특정 기간 동안 발의된 법안의 주요 내용을 수집합니다.

In [6]:
# 최근 날짜로 테스트 
target_date = (datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d')
today_date = datetime.now().strftime('%Y-%m-%d')

latest_bills_df = fetcher.fetch_bills_data(start_date=target_date, end_date=today_date, age="22")

if latest_bills_df is not None and not latest_bills_df.empty:
    print(f"Successfully fetched {len(latest_bills_df)} bills.")
    display(latest_bills_df.head(3))
else:
    print("No bills found for the specified period.")

📌 [2025-11-23 ~ 2025-11-30] 의안 주요 내용 데이터 수집 시작...
➡️  첫 페이지 요청하여 전체 데이터 개수 확인 중...

📥 데이터 수집 중: 100%|██████████| 244/244 [00:00<00:00, 180.65개/s]

🎉 다운로드 완료! 총 244개의 데이터를 수집했습니다. 📊
✅ [INFO] 총 244 개의 법안 수집됨.
✅ [INFO] 데이터 컬럼 필터링을 수행합니다.
✅ [INFO] 결측치 처리 완료. 239 개의 법안 유지됨.

📌 발의일자별 수집한 데이터 수:
proposeDate
2025-11-26    65
2025-11-27    56
2025-11-28    52
2025-11-25    34
2025-11-24    32
Name: count, dtype: int64
Successfully fetched 239 bills.

,proposeDate,billId,billName,billNumber,summary,stage,proposerKind,assemblyNumber
0,2025-11-28,PRC_Y2W5E1F1D2E4C1D1B4J4K5I4I7H9I0,출입국관리법 일부개정법률안(전용기의원 등 15인),2214729,제안이유 및 주요내용\r\n\r\n 주택도시보증공사는 전세보증금 미반환 시 임차인...,접수,의원,22
1,2025-11-28,PRC_L2L5T1U1S2T4R1S1Q4M3M3L9L0K8K9,주택도시기금법 일부개정법률안(전용기의원 등 16인),2214728,제안이유 및 주요내용\r\n\r\n 주택도시보증공사는 전세보증금 미반환 시 임차인...,접수,의원,22
2,2025-11-28,PRC_N2M5N0L6L2H7G1G6E1F2D4E6M6M1L5,성폭력범죄의 처벌 등에 관한 특례법 일부개정법률안(박은정의원 등 12인),2214727,제안이유 및 주요내용\r\n\r\n 현행법은 강간과 추행의 죄 및 그 가중적 구성...,접수,의원,22

In [5]:
# API 동작 확인을 위해 정해진 날짜로 테스트
bills_df = fetcher.fetch_bills_data(start_date="2025-07-11", end_date="2025-07-11", age="22")

if bills_df is not None and not bills_df.empty:
    print(f"Successfully fetched {len(bills_df)} bills.")
    display(bills_df.head(3))
else:
    print("No bills found for the specified period.")

📌 [2025-07-11 ~ 2025-07-11] 의안 주요 내용 데이터 수집 시작...
➡️  첫 페이지 요청하여 전체 데이터 개수 확인 중...

📥 데이터 수집 중: 100%|██████████| 27/27 [00:00<?, ?개/s]

🎉 다운로드 완료! 총 27개의 데이터를 수집했습니다. 📊
✅ [INFO] 총 27 개의 법안 수집됨.
✅ [INFO] 데이터 컬럼 필터링을 수행합니다.
✅ [INFO] 결측치 처리 완료. 27 개의 법안 유지됨.

📌 발의일자별 수집한 데이터 수:
proposeDate
2025-07-11    27
Name: count, dtype: int64
Successfully fetched 27 bills.

,proposeDate,billId,billName,billNumber,summary,stage,proposerKind,assemblyNumber
0,2025-07-11,PRC_W2U5V0T6T1C7C1A7B0Z6Y5Y7G1G3F8,청원경찰법 일부개정법률안(모경종의원 등 23인),2211457,제안이유 및 주요내용\r\n\r\n 국가기관 또는 지방자치단체 소속 청원경찰은 국...,소관위심사,의원,22
1,2025-07-11,PRC_P2Q5P0W6X1V1W1U8V2T2U5P9O0O0N4,노인복지법 일부개정법률안(전진숙의원 등 10인),2211456,"제안이유 및 주요내용\r\n\r\n 초고령 사회 진입에 따라, 만성질환, 복합질환...",소관위심사,의원,22
2,2025-07-11,PRC_E2D5B0C6A1B3I1J1I2I1G1H4F5N8O8,산업안전보건법 일부개정법률안(정혜경의원 등 14인),2211455,"제안이유\r\n\r\n 현행법은 작업중지권을 보장하고 있으나, 기후위기 등의 노동...",소관위심사,의원,22

## 4. 공동발의자 정보 수집 (`fetch_bills_coactors`)
위에서 수집한 법안(`bills_df`)에 대한 공동발의자 정보를 수집합니다.

In [ ]:
# bills_df가 메모리에 있으면 자동으로 사용합니다.
coactors_df = fetcher.fetch_bills_coactors(df_bills=bills_df.head(5))

if coactors_df is not None and not coactors_df.empty:
    print(f"Successfully fetched coactors for {len(coactors_df)} bills.")
    display(coactors_df.head(3))
else:
    print("Failed to fetch coactors data.")

📌 [INFO] 대표/공동 발의자 정보 수집 시작... 총 5개의 법안 대상

발의자 수집:  20%|██        | 1/5 [00:00<00:00,  5.67건/s]

➡️  첫 페이지 요청하여 전체 데이터 개수 확인 중...
⚠️  수집할 데이터가 없거나 API 응답에 문제가 있습니다.
⚠️ [WARN] billId PRC_W2U5V0T6T1C7C1A7B0Z6Y5Y7G1G3F8에 대한 발의자 데이터를 찾을 수 없습니다.
➡️  첫 페이지 요청하여 전체 데이터 개수 확인 중...

발의자 수집:  40%|████      | 2/5 [00:00<00:00,  4.89건/s]

⚠️  수집할 데이터가 없거나 API 응답에 문제가 있습니다.
⚠️ [WARN] billId PRC_P2Q5P0W6X1V1W1U8V2T2U5P9O0O0N4에 대한 발의자 데이터를 찾을 수 없습니다.
➡️  첫 페이지 요청하여 전체 데이터 개수 확인 중...
⚠️  수집할 데이터가 없거나 API 응답에 문제가 있습니다.

발의자 수집:  80%|████████  | 4/5 [00:00<00:00,  5.40건/s]

⚠️ [WARN] billId PRC_E2D5B0C6A1B3I1J1I2I1G1H4F5N8O8에 대한 발의자 데이터를 찾을 수 없습니다.
➡️  첫 페이지 요청하여 전체 데이터 개수 확인 중...
⚠️  수집할 데이터가 없거나 API 응답에 문제가 있습니다.
⚠️ [WARN] billId PRC_B2C5A0B6J0J5I1G3G2F7G4B4C7B1Z0에 대한 발의자 데이터를 찾을 수 없습니다.
➡️  첫 페이지 요청하여 전체 데이터 개수 확인 중...

발의자 수집: 100%|██████████| 5/5 [00:00<00:00,  5.11건/s]

⚠️  수집할 데이터가 없거나 API 응답에 문제가 있습니다.
⚠️ [WARN] billId PRC_K2K5S0R6R0P5Q1P3P2X7Y0W6U4V5T0에 대한 발의자 데이터를 찾을 수 없습니다.
⚠️ [INFO] 공동발의자 정보를 확보하지 못한 5개 법안을 제외했습니다.
✅ [INFO] 발의자 정보 수집 완료. 총 0개의 법안에 대한 데이터를 확보했습니다.
Failed to fetch coactors data.

## 5. 의정활동 타임라인 수집 (`fetch_bills_timeline`)
법안 심사 진행 단계 등 의정활동 내역을 수집합니다.
- 해당 메서드는 데이터 수집에만 책임을 가짐. 컬럼 필터링은 WorkFlowManager 클래스의 update_bills_timeline 메서드에서 수행

In [ ]:
timeline_df = fetcher.fetch_bills_timeline(start_date='2025-07-11', end_date='2025-07-11', age='22')

if timeline_df is not None and not timeline_df.empty:
    print(f"Successfully fetched {len(timeline_df)} timeline events.")
    display(timeline_df.head(3))
else:
    print("No timeline data found.")

📌 [INFO] [2025-07-11 ~ 2025-07-11] 의정활동 데이터 수집 시작...
✅ [INFO] 2025-07-11 | 📄 Page 1 | 📊 81 개 추가됨. 총 81 개 수집됨.

✅ [INFO] 모든 파일 다운로드 완료! ⏳ 전체 소요 시간: 0.53초
📌 [INFO] 총 81 개의 의정활동 데이터 수집됨.
Successfully fetched 81 timeline events.

,SEQ,DT,BILL_KIND,AGE,BILL_NO,BILL_NM,STAGE,DTL_STAGE,COMMITTEE,ACT_STATUS,BILL_ID,LINK_URL,COMMITTEE_ID
0,1000335355955,2025-07-11,법률안,22,2201739,양봉산업의 육성 및 지원에 관한 법률 일부개정법률안(임호선의원 등 16인),정부이송,정부이송,-,정부이송,PRC_N2V4W0U6U1T0T1S5S3O1M5N2M4M5K9,https://likms.assembly.go.kr/bill/billDetail.d...,None
1,1000335355945,2025-07-11,법률안,22,2201852,생활체육진흥법 일부개정법률안(임오경의원 등 10인),정부이송,정부이송,-,정부이송,PRC_J2J4I0G7H1P6P1O5O5M1L2M3H9I3G0,https://likms.assembly.go.kr/bill/billDetail.d...,None
2,1000335355929,2025-07-11,법률안,22,2201941,스마트농업 육성 및 지원에 관한 법률 일부개정법률안(문대림의원 등 17인),정부이송,정부이송,-,정부이송,PRC_F2D4L0M7K1L5J1I7I3E9F2D0D3C7A4,https://likms.assembly.go.kr/bill/billDetail.d...,None

## 6. 법안 결과 데이터 수집 (`fetch_bills_result`)
법안의 최종 처리 결과(가결, 부결, 폐기 등)를 수집합니다.

In [ ]:
# 결과가 많이 나오는 본회의 날짜 주변으로 설정
result_df = fetcher.fetch_bills_result(start_date='2025-07-03', end_date='2025-07-03', age='22')

if result_df is not None and not result_df.empty:
    print(f"Successfully fetched {len(result_df)} bill results.")
    display(result_df.head(3))
else:
    print("No bill results found.")

📌 [INFO] [2025-07-03 ~ 2025-07-03] 법안 결과 데이터 수집 시작...
✅ [INFO] 2025-07-03 | 📄 Page 1 | 📊 Total: 79 개 수집됨.

✅ [INFO] 모든 파일 다운로드 완료! ⏳ 전체 소요 시간: 0.30초
📌 [INFO] 총 79 개의 법안 수집됨.
Successfully fetched 79 bill results.

,BILL_ID,BILL_NO,AGE,BILL_NAME,PROPOSER,PROPOSER_KIND,PROPOSE_DT,CURR_COMMITTEE_ID,CURR_COMMITTEE,COMMITTEE_DT,COMMITTEE_PROC_DT,LINK_URL,RST_PROPOSER,LAW_PROC_RESULT_CD,LAW_PROC_DT,LAW_PRESENT_DT,LAW_SUBMIT_DT,CMT_PROC_RESULT_CD,CMT_PROC_DT,CMT_PRESENT_DT,RST_MONA_CD,PROC_RESULT_CD,PROC_DT
0,PRC_F2K5P0F6H2D4X0S8P3R1V5C6G8G4J5,2211253,22,군급식기본법안(대안),국방위원장,위원장,2025-07-03,9700019,국방위원회,None,None,https://likms.assembly.go.kr/bill/billDetail.d...,None,수정가결,2025-07-03,2025-07-03,2025-06-25,대안가결,2025-06-25,2025-06-25,None,원안가결,2025-07-03
1,PRC_F2O5G0P6F2C4P0C8M2P9N2R2S6W8X8,2211252,22,계엄법 일부개정법률안(대안),국방위원장,위원장,2025-07-03,9700019,국방위원회,None,None,https://likms.assembly.go.kr/bill/billDetail.d...,None,수정가결,2025-07-03,2025-07-03,2025-06-25,대안가결,2025-06-25,2025-06-25,None,원안가결,2025-07-03
2,PRC_P2M5I0P7H0Z2V1Q8N3K0C1E0U1L4S6,2211251,22,상법 일부개정법률안(대안),법제사법위원장,위원장,2025-07-03,9700006,법제사법위원회,None,None,https://likms.assembly.go.kr/bill/billDetail.d...,None,None,None,None,None,대안가결,2025-07-03,2025-07-03,None,원안가결,2025-07-03

## 7. 본회의 표결 데이터 수집 (`fetch_bills_vote`)
본회의에서 이루어진 표결 정보를 수집합니다.

In [5]:
vote_df = fetcher.fetch_bills_vote(start_date='2025-07-03', end_date='2025-07-03', age='22')

if vote_df is not None and not vote_df.empty:
    print(f"Successfully fetched {len(vote_df)} votes.")
    display(vote_df.head(3))
else:
    print("No vote data found.")

📌 [INFO] [2025-07-03 ~ 2025-07-03] 본회의 의결 데이터 수집 시작...
✅ [INFO] 2025-07-03 | 📄 Page 1 | 📊 Total: 16 개 수집됨.

✅ [INFO] 모든 파일 다운로드 완료! ⏳ 전체 소요 시간: 0.22초
📌 [INFO] 총 16 개의 본회의 의결 데이터 수집됨.
Successfully fetched 16 votes.

,AGE,BILL_NO,BILL_NM,BILL_KIND,PROPOSER,COMMITTEE_NM,PROC_RESULT_CD,VOTE_TCNT,YES_TCNT,NO_TCNT,...,LAW_SUBMIT_DT,LAW_PRESENT_DT,LAW_PROC_DT,RGS_PRESENT_DT,RGS_PROC_DT,CURR_TRANS_DT,ANNOUNCE_DT,BILL_ID,LINK_URL,CURR_COMMITTEE_ID
0,22,2211250,출입국관리법 일부개정법률안(대안)(법제사법위원장),법률안,법제사법위원장,법제사법위원회,원안가결,275,274,None,...,None,None,None,2025-07-03,2025-07-03,2025-07-11,2025-07-22,PRC_A2Y5N0J7W0L2U1Q8C3H1Y5N0J3K0D9,https://likms.assembly.go.kr/bill/billDetail.d...,9700006
1,22,2211251,상법 일부개정법률안(대안)(법제사법위원장),법률안,법제사법위원장,법제사법위원회,원안가결,272,218,29,...,None,None,None,2025-07-03,2025-07-03,2025-07-11,2025-07-22,PRC_P2M5I0P7H0Z2V1Q8N3K0C1E0U1L4S6,https://likms.assembly.go.kr/bill/billDetail.d...,9700006
2,22,2211249,탄소중립에 따른 한우산업 전환 및 지원에 관한 법률안(대안)(농림축산식품해양수산위원장),법률안,농림축산식품해양수산위원장,농림축산식품해양수산위원회,원안가결,266,263,None,...,2025-06-23,2025-07-03,2025-07-03,2025-07-03,2025-07-03,2025-07-11,2025-07-22,PRC_Y2J5P0C6O1D8D1L3K3T5Y0Q8G8E5H9,https://likms.assembly.go.kr/bill/billDetail.d...,9700408

## 8. 정당별 표결 결과 집계 (`fetch_vote_party`)
수집된 표결 데이터(`vote_df`)를 바탕으로 정당별 찬성표를 집계합니다.

In [7]:
# vote_df가 메모리에 있으면 자동으로 사용합니다.
party_vote_df = fetcher.fetch_vote_party(df_vote=vote_df.head(5))

if party_vote_df is not None and not party_vote_df.empty:
    print(f"Successfully aggregated party votes for {len(party_vote_df)} entries.")
    display(party_vote_df)
else:
    print("Failed to aggregate party votes.")

📌 [INFO] 법안별 정당별 투표 결과 데이터 수집 시작...

정당별 투표 수집:  20%|██        | 1/5 [00:00<00:03,  1.18법안/s]

✅ [INFO] PRC_A2Y5N0J7W0L2U1Q8C3H1Y5N0J3K0D9 | 📊 298 개 데이터 수집됨.

정당별 투표 수집:  40%|████      | 2/5 [00:01<00:02,  1.28법안/s]

✅ [INFO] PRC_P2M5I0P7H0Z2V1Q8N3K0C1E0U1L4S6 | 📊 298 개 데이터 수집됨.

정당별 투표 수집:  60%|██████    | 3/5 [00:02<00:01,  1.30법안/s]

✅ [INFO] PRC_Y2J5P0C6O1D8D1L3K3T5Y0Q8G8E5H9 | 📊 298 개 데이터 수집됨.

정당별 투표 수집:  80%|████████  | 4/5 [00:03<00:00,  1.25법안/s]

✅ [INFO] PRC_O2M5A0C6M1Q8Y1X3L2C4F0P2M0K3I5 | 📊 298 개 데이터 수집됨.

정당별 투표 수집: 100%|██████████| 5/5 [00:03<00:00,  1.29법안/s]

✅ [INFO] PRC_F2K5P0F6H2D4X0S8P3R1V5C6G8G4J5 | 📊 298 개 데이터 수집됨.

✅ [INFO] 모든 파일 다운로드 완료! ⏳ 전체 소요 시간: 3.89초
📌 [INFO] 총 1490 개의 개별 투표 데이터 수집됨.
Successfully aggregated party votes for 40 entries.

                                billId partyName  voteForCount
0   PRC_A2Y5N0J7W0L2U1Q8C3H1Y5N0J3K0D9      개혁신당             3
1   PRC_A2Y5N0J7W0L2U1Q8C3H1Y5N0J3K0D9      국민의힘            92
2   PRC_A2Y5N0J7W0L2U1Q8C3H1Y5N0J3K0D9     기본소득당             1
3   PRC_A2Y5N0J7W0L2U1Q8C3H1Y5N0J3K0D9    더불어민주당           159
4   PRC_A2Y5N0J7W0L2U1Q8C3H1Y5N0J3K0D9       무소속             3
5   PRC_A2Y5N0J7W0L2U1Q8C3H1Y5N0J3K0D9     사회민주당             1
6   PRC_A2Y5N0J7W0L2U1Q8C3H1Y5N0J3K0D9     조국혁신당            12
7   PRC_A2Y5N0J7W0L2U1Q8C3H1Y5N0J3K0D9       진보당             3
8   PRC_F2K5P0F6H2D4X0S8P3R1V5C6G8G4J5      개혁신당             3
9   PRC_F2K5P0F6H2D4X0S8P3R1V5C6G8G4J5      국민의힘            88
10  PRC_F2K5P0F6H2D4X0S8P3R1V5C6G8G4J5     기본소득당             1
11  PRC_F2K5P0F6H2D4X0S8P3R1V5C6G8G4J5    더불어민주당           155
12  PRC_F2K5P0F6H2D4X0S8P3R1V5C6G8G4J5       무소속             3
13  PRC_F2K5P0F6H2D4X0S8P3R1V5C6G8G4J5     사회민주당             1
14  PRC_F2K5P0F6H2D4X0S8P3R1V5C6G8G4J5     조국혁신당            11
15  PRC_F2K5P0F6H2D4X0S8P3R1V5C6G8G4J5       진보당             3
16  PRC_O2M5A0C6M1Q8Y1X3L2C4F0P2M0K3I5      개혁신당             3
17  PRC_O2M5A0C6M1Q8Y1X3L2C4F0P2M0K3I5      국민의힘            88
18  PRC_O2M5A0C6M1Q8Y1X3L2C4F0P2M0K3I5     기본소득당             1
19  PRC_O2M5A0C6M1Q8Y1X3L2C4F0P2M0K3I5    더불어민주당           151
20  PRC_O2M5A0C6M1Q8Y1X3L2C4F0P2M0K3I5       무소속             3
21  PRC_O2M5A0C6M1Q8Y1X3L2C4F0P2M0K3I5     사회민주당             1
22  PRC_O2M5A0C6M1Q8Y1X3L2C4F0P2M0K3I5     조국혁신당            12
23  PRC_O2M5A0C6M1Q8Y1X3L2C4F0P2M0K3I5       진보당             3
24  PRC_P2M5I0P7H0Z2V1Q8N3K0C1E0U1L4S6      개혁신당             3
25  PRC_P2M5I0P7H0Z2V1Q8N3K0C1E0U1L4S6      국민의힘            35
26  PRC_P2M5I0P7H0Z2V1Q8N3K0C1E0U1L4S6     기본소득당             1
27  PRC_P2M5I0P7H0Z2V1Q8N3K0C1E0U1L4S6    더불어민주당           160
28  PRC_P2M5I0P7H0Z2V1Q8N3K0C1E0U1L4S6       무소속             3
29  PRC_P2M5I0P7H0Z2V1Q8N3K0C1E0U1L4S6     사회민주당             1
30  PRC_P2M5I0P7H0Z2V1Q8N3K0C1E0U1L4S6     조국혁신당            12
31  PRC_P2M5I0P7H0Z2V1Q8N3K0C1E0U1L4S6       진보당             3
32  PRC_Y2J5P0C6O1D8D1L3K3T5Y0Q8G8E5H9      개혁신당             3
33  PRC_Y2J5P0C6O1D8D1L3K3T5Y0Q8G8E5H9      국민의힘            88
34  PRC_Y2J5P0C6O1D8D1L3K3T5Y0Q8G8E5H9     기본소득당             1
35  PRC_Y2J5P0C6O1D8D1L3K3T5Y0Q8G8E5H9    더불어민주당           152
36  PRC_Y2J5P0C6O1D8D1L3K3T5Y0Q8G8E5H9       무소속             3
37  PRC_Y2J5P0C6O1D8D1L3K3T5Y0Q8G8E5H9     사회민주당             1
38  PRC_Y2J5P0C6O1D8D1L3K3T5Y0Q8G8E5H9     조국혁신당            12
39  PRC_Y2J5P0C6O1D8D1L3K3T5Y0Q8G8E5H9       진보당             3

## 9. 대안 법안 정보 수집 (`fetch_bills_alternatives`)
대안반영폐기된 법안들의 대안 법안 정보를 수집합니다.
테스트를 위해 대안이 포함될 가능성이 높은 법안 목록을 먼저 확보합니다.

In [9]:
# 대안반영폐기된 법안이 포함된 데이터를 수집 (예: 2024년 2월)
alt_bills_df = fetcher.fetch_bills_data(start_date="2025-07-11", end_date="2025-07-11", age="22")

# 대안 수집 실행
alternatives_df = fetcher.fetch_bills_alternatives(df_bills=alt_bills_df)

if alternatives_df is not None and not alternatives_df.empty:
    print(f"Successfully fetched {len(alternatives_df)} alternative bill relations.")
    display(alternatives_df.head(3))
else:
    print("No alternative bills found.")

📌 [2025-07-11 ~ 2025-07-11] 의안 주요 내용 데이터 수집 시작...
➡️  첫 페이지 요청하여 전체 데이터 개수 확인 중...

📥 데이터 수집 중: 100%|██████████| 27/27 [00:00<?, ?개/s]

🎉 다운로드 완료! 총 27개의 데이터를 수집했습니다. 📊
✅ [INFO] 총 27 개의 법안 수집됨.
✅ [INFO] 데이터 컬럼 필터링을 수행합니다.
✅ [INFO] 결측치 처리 완료. 27 개의 법안 유지됨.

📌 발의일자별 수집한 데이터 수:
proposeDate
2025-07-11    27
Name: count, dtype: int64
📌 [INFO] 법안별 대안 데이터 수집 시작...

대안 법안 수집: 100%|██████████| 27/27 [00:05<00:00,  4.52it/s]

⚠️ [WARNING] 대안 법안 데이터를 수집하지 못했습니다.
No alternative bills found.